debug: 1                    # Range 0-4 (0 means no debug statements will print)

device: /dev/ttyACM0
frame_id: gps #TODO: change it in the future
config_on_startup: false
uart1:
  baudrate: 115200
rate: 1
nav_rate: 1
publish:
  all: true
# tmode3: 1 # survey-in
# # Enable u-blox message publishers

#   nav:
#     all: true
#     relposned: true
#     posllh: true
#     posecef: true
# sv_in:
#   reset: false              # True: disables and re-enables survey-in (resets)
#                             # False: Disables survey-in only if TMODE3 is
#                             # disabled
#   min_dur: 300              # Survey-In Minimum Duration [s]
#   acc_lim: 3.0              # Survey-In Accuracy Limit [m]
