ekf_se_map:
  frequency: 2
  two_d_mode: true
  print_diagnostics: true
  publish_tf: true

  map_frame: map
  odom_frame: odom
  base_link_frame: gps
  world_frame: map

  odom0: odometry/gps
  odom0_config: [true,  true,  false,
                false, false, false,
                false, false, false,
                false, false, false,
                false, false, false]

  imu0: gps/navheading
  imu0_config: [false, false, false,
                false,  false,  true,
                false, false, false,
                false,  false,  false,
                false,  false,  false]
  imu0_nodelay: false
  imu0_differential: false
  imu0_relative: true
  imu0_queue_size: 5

ekf_se_odom:
  frequency: 2
  two_d_mode: true
  print_diagnostics: true
  publish_tf: true

  map_frame: map
  odom_frame: odom
  base_link_frame: gps
  world_frame: odom

  odom0: odometry/gps
  odom0_config: [true,  true,  false,
                false, false, false,
                false, false, false,
                false, false, false,
                false, false, false]

  imu0: gps/navheading
  imu0_config: [false, false, false,
                false,  false,  true,
                false, false, false,
                false,  false,  false,
                false,  false,  false]
  imu0_nodelay: false
  imu0_differential: false
  imu0_relative: true
  imu0_queue_size: 5

navsat_transform:
  frequency: 30
  delay: 3.0
  zero_altitude: false
  broadcast_utm_transform: true
  publish_filtered_gps: true
  use_odometry_yaw: false
  wait_for_datum: false
